In [4]:
import numpy as np
import pandas as pd

In [253]:
x = pd.get_dummies(np.arange(3))
x1 = x[0].values.reshape(-1, 1)
x2 = x[1].values.reshape(-1, 1)
x3 = x[2].values.reshape(-1, 1)

w1 = np.repeat(1, 3)
w2 = np.repeat(-1, 3)
w = np.column_stack([w1, w2])
b = np.row_stack([0.3, 0.7])
h_0 = np.zeros_like(b)
w

array([[ 1, -1],
       [ 1, -1],
       [ 1, -1]])

In [41]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [236]:
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x))

In [237]:
def cell(h_t1, x_input):
    w_x = np.column_stack([np.repeat(1, 3), np.repeat(-1, 3)])
    w_h = np.column_stack([np.repeat(1, 2), np.repeat(0.2, 2)])
    b = np.row_stack([0.3, 0.7])
    
    output = np.matmul(w_h.transpose(), h_t1) + np.matmul(w_x.transpose(), x_input) + b
    output = sigmoid(output)
    
    return output

In [238]:
def output_layer(h_layer):
    w_out = np.column_stack(([0.3, 0.2], [1, -1], [0.3, 1]))
    
    b = np.repeat(0.5, 3).reshape(-1, 1)
    output = np.dot(w_out.T, h_layer) + b
    
    return output

In [250]:
def RNN(h_previous, x_input):
    h_0 = np.zeros(shape=[2, 1])
    h_1 = cell(h_previous, x_input)

    out = output_layer(h_1)
    out = softmax(out)
    
    return h_1, out

In [252]:
init_h = np.zeros_like(b)
h_11, out1 = RNN(init_h, x1)
print(h_11)
print(out1)

[[ 0.78583498]
 [ 0.42555748]]
[[ 0.29021031]
 [ 0.30187752]
 [ 0.40791216]]


In [256]:
h_12, out2 = RNN(h_11, x2)
print(h_12)
print(out2)

[[ 0.92493663]
 [ 0.48557363]]
[[ 0.28235689]
 [ 0.30124959]
 [ 0.41639351]]


In [257]:
h_13, out3 = RNN(h_12, x3)
print(h_13)
print(out3)

[[ 0.93764399]
 [ 0.49552563]]
[[ 0.28167754]
 [ 0.29961041]
 [ 0.41871205]]
